#!/bin/sh

display_separator() {
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}

display_separator
echo 'Gradle assemble..'
./gradlew assemble

display_separator
echo 'Building docker image..'
docker compose -f ./local/compose.yml build

display_separator
echo 'Restarting docker service..'
docker compose -f ./local/compose.yml up -d --force-recreate resource
