#!/bin/sh

display_separator() {
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}

display_separator
echo 'Shutting down running docker services..'
docker compose -f ./local/compose.yml down --remove-orphans
