logging:
  level:
    org.springframework.security: trace

server:
  port : 80

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}

oauth2:
  introspection:
    url: ${OAUTH2_INTROSPECTION_URL}
    token: ${OAUTH2_INTROSPECTION_TOKEN}
